# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://root:@127.0.0.1:3306/pi_projet?serverVersion=8.0.32&charset=utf8mb4
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Application Configuration
spring.application.name=forum
server.port=8080

